[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.8.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-lifecycle-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.0"

androidx-material = "com.google.android.material:material:1.6.1"

androidx-compose-ui = "androidx.compose.ui:ui:1.3.0-alpha01"
androidx-compose-material = "androidx.compose.material:material:1.3.0-alpha01"
androidx-compose-toolingPreview = "androidx.compose.ui:ui-tooling-preview:1.3.0-alpha01"
androidx-compose-activity = "androidx.activity:activity-compose:1.5.0"
androidx-compose-tooling = "androidx.compose.ui:ui-tooling:1.3.0-alpha01"
